Sprint 5
MarinaKolbina/MovieQuiz-ios pull request #4
Opened 2022-10-25 21:26 UTC by MarinaKolbina

2022-10-26 10:03 UTC, ABashkirova requested changes
Очень хорошая работа, нужны минимальные исправления

2022-10-26 10:03 UTC, ABashkirova commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    let viewController: UIViewController?
Здесь сохраняется сильная ссылка на вью контроллер и получается retain cycle

2022-10-26 10:03 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +//
Предлагаю сохранять эксперименты с кодом в отдельной ветке :) а на ревью отдавать чистый код, без лишних комментариев. 

(Понимаю, сложно расстаться с интересными кусочками, но и не нужно, гит все помнит)

2022-10-26 10:03 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +                    self.questionFactory?.requestNextQuestion()
здесь не сбрасывается результат последнего вопроса, поэтому пользователь увидит рамку на первом вопросе, давайте вынесем это в отдельную функцию и до сбросим состояние полноценно?

например в функцию resetGame()

2022-10-26 10:03 UTC, ABashkirova commented on MovieQuiz/Services/StatisticService.swift
> +    var totalAccuracy: Double {
Здесь все очень хорошо написано

2022-10-27 20:39 UTC, MarinaKolbina commented on MovieQuiz/Services/StatisticService.swift
> +    var totalAccuracy: Double {
Благодарю! :)))

2022-10-28 10:20 UTC, MarinaKolbina commented on MovieQuiz/Services/StatisticService.swift
> +    var totalAccuracy: Double {
@ABashkirova могу я задать вопрос по комментариям в практикуме? там было два замечания касательно contentMode (это исправлено) и скругления углов (в соответствии с макетом, стоит 20, не понимаю, в чем там может быть ошибка?)

2022-10-28 13:18 UTC, ABashkirova commented on MovieQuiz/Services/StatisticService.swift
> +    var totalAccuracy: Double {
Да, конечно

по макетам 20, и в сториборде такое значение. Но как только вы рисуете рамку, значение для угла задаете новое, и тут уже расхождение с фирмой идет. 
<img width="523" alt="Screenshot 2022-10-28 at 17 16 55" src="https://user-images.githubusercontent.com/20269264/198604013-b845c78a-4f79-46e3-be85-e9ff6a78b5be.png">

2022-10-28 13:19 UTC, ABashkirova commented on MovieQuiz/Services/StatisticService.swift
> +    var totalAccuracy: Double {
cornerRadius, masksToBounds - эти параметры в нашей задаче можно задавать один раз, они не меняются в зависимости от ответа

2022-11-07 14:53 UTC, merged